### ISSUE TITLE
Any comments on what "capacity" means in the VAE model?

### ISSUE THREAD

**Issue by yeswecan** [caillonantoine/RAVE#13]
Hello there and thanks for stunning work!

I'm trying to do a timbre transfer continuously, encoding input audio buffer by buffer and concatenating them after decoding. The question is, what is the preferred way of doing that? Is it better to encode longer sequences or does it matter in any way? I know the paper discussing the realtime usage is coming, but still, in the context of the VAE, does the length of the input audio affect the latents produced by the encoder?

I realise it must have something to do with the Capacity parameter but I didn't yet get through all the code:). I would appreciate the response.

If I were to word it like an issue, a few words on how the input length affects the way the audio is encoded would be awesome. Thanks a bunch!

**Comment by caillonantoine** [comment]
Hi ! Capacity defines how "big" the model is in term of hidden layers dimensionality, so it does not affect the receptive field of the model (i.e how many audio samples are taken into account). By default, RAVE has a receptive field of approximately 500ms.

If you give RAVE a sample that is smaller than its receptive field, it might throw an error, or produce less consistent results. For now I would say keep the samples big enough (2-3s) so that there is enough context to produce coherent results.

For your application, encoding small buffers (> 2048) might work, but would results in painful discontinuities in the synthesized audio if you simply cat the produced output. For now you might wan't to produce longer buffers (> 2s) and use overlap add to produce a "pleasing" transition between buffers ! :)

**Comment by yeswecan** [comment]
> Hi ! Capacity defines how "big" the model is in term of hidden layers dimensionality, so it does not affect the receptive field of the model (i.e how many audio samples are taken into account). By default, RAVE has a receptive field of approximately 500ms.
> 
> If you give RAVE a sample that is smaller than its receptive field, it might throw an error, or produce less consistent results. For now I would say keep the samples big enough (2-3s) so that there is enough context to produce coherent results.
> 
> For your application, encoding small buffers (> 2048) might work, but would results in painful discontinuities in the synthesized audio if you simply cat the produced output. For now you might wan't to produce longer buffers (> 2s) and use overlap add to produce a "pleasing" transition between buffers ! :)

Thank you Antoine! Your answer is immensely helpful, I will add a memory for more consistent synthesis. May I also ask you how do you set the receptive field during training? I might experiment with that.

**Comment by caillonantoine** [comment]
You can't really define your receptive field, but you can increase / decrease it by adding / removing layers (see the ratio parameter) ! Good luck :)
